### ISSUE TITLE
Add astropy units

### ISSUE THREAD

**Issue by Physarah** [pykoala/koala#10]
Difficult to follow anything without units. And I would get rid of the hard coded definitions of the speed of light / parsecs etc at the start. `astropy.constants` should be used
```
pc=3.086E18    # pc in cm
C =299792.458  # c in km/s
```

**Comment by aragilar** [comment]
I'd avoid using astropy.constants for now, let's create a constants module, and once we're sure that there's no changes based the value of the constants, switch to astropy.constants then.
