### ISSUE TITLE
Work out how to handle pysynphot

### ISSUE THREAD

**Issue by aragilar** [pykoala/koala#2]
see https://github.com/spacetelescope/pysynphot/pull/106/files

**Comment by Physarah** [comment]
Pysynphot is only in two functions, `rebin_spec` and `rebin_spec_shift` and in these functions is used once. Considering pysynphot requires you to download a lot of calibration files to run (or throws warnings if you don't) and as @YourLocalBlake has mentioned, doesn't run on windows, let's try to strip this out.

**Comment by Physarah** [comment]
Interesting discussion on here, the code seems to come straight from [this post](https://www.astrobetter.com/blog/2013/08/12/python-tip-re-sampling-spectra-with-pysynphot/)

**Comment by YourLocalBlake** [comment]
Depending on how integrated the functions seem to be implemented we could just move from pysynphot to just synphot as mentioned in the road map -  https://github.com/spacetelescope/pysynphot/pull/106/files

I did a quick and dirty conversion of the main code to 3.7 and synphot appeared to complete properly. Synphot, as compared to pysynphot, appears to work on windows as well

**Comment by YourLocalBlake** [comment]
Currently the package synphot will cause circleCI to fail as it cannot be build from wheels. See error "Could not build wheels for synphot which use PEP 517 and cannot be installed directly"
