### ISSUE TITLE
Bors timing out on PRs

### ISSUE THREAD

**Issue by YourLocalBlake** [pykoala/koala#253]
Currently Bors will timeout with codecov/patch and codecov/project still specified as running and pykoala succeeding on azure pipelines.

**Comment by aragilar** [comment]
Looks like codecov is failing to upload the coverage report (given their script isn't exiting with a non-zero error when there's an failure to upload, there's some issue with their script), looks like either the script needs to be updated to a new azure API or azure pipelines is broken...

Quickest fix is to comment out the lines in the bors.toml.

**Comment by YourLocalBlake** [comment]
Alright, I'll comment it out as a temporarily measure. 
#254

**Comment by aragilar** [comment]
Looks like codecov is getting rid of that script anyway: see https://github.com/codecov/codecov-bash and https://about.codecov.io/blog/introducing-codecovs-new-uploader/

Once you've cleared the backlog of PRs, you could see if their new uploader works or not.

**Comment by YourLocalBlake** [comment]
Alright thanks. I'll get around to it eventually

**Comment by YourLocalBlake** [comment]
see #256
