### ISSUE TITLE
Add sky_lines.dat and ssoextinct.dat files

### ISSUE THREAD

**Issue by YourLocalBlake** [pykoala/koala#37]
sky_lines.dat is required to use the `sky_method="1Dfit"` and ssoextinct.dat is required to use `do_extinction=True` when using `KOALA_RSS`

**Comment by angelrls** [comment]
Hi Blake. Yes, there are 3 extra .dat files that are needed (those two and another more). I'm talking to @aragilar to upload them now.

**Comment by angelrls** [comment]
Done!
