### ISSUE TITLE
Tutorial reduction_sequence_science

### ISSUE THREAD

**Issue by miguelglezb** [pykoala/koala#410]
It references two undefined functions: 

- `rss_info_template` in line:
`from pykoala.instruments.koala_ifu import koala_rss`

- `koala_rss` in line:
`from pykoala.instruments.koala_ifu import koala_rss`

Many of the cells depends in these two functions, so they fail.

**Comment by PabloCorcho** [comment]
There were a couple of issues that I overlooked in PR #408. I created a quick PR to fix these issues #411.

**Comment by miguelglezb** [comment]
Those issues are fixed, but now it has the same issue as `reduction_sequence_std_stars` that is, `pykoala.mplstyle` is not a valid package style.

**Comment by PabloCorcho** [comment]
On hold until #414 is solved.
