### ISSUE TITLE
Add option of subtract a 2D sky

### ISSUE THREAD

**Issue by angelrls** [pykoala/koala#434]
I'm creating a 2D sky object, but it fails when applying substract() as the option of using a 2D sky is not included there (and it should be).

Please, I need the this code below as new lines 166-168 in sky.py:

```
elif data.ndim == 2 and self.intensity.ndim == 2:  
            skymodel_intensity = self.intensity       
            skymodel_var = self.variance     
```                

It is 1 of the only 2 changes I need to implement in the main code after checking rss.koala tasks and my 3 tutorials with the latest version of the code to make it working. 

I have done these 2 changes in my local version but I will only push (with the help of Miguel) my new files.

Thanks,

**Comment by PabloCorcho** [comment]
This is fixed in #438
