### ISSUE TITLE
Split out `koala.__init__.py`

### ISSUE THREAD

**Issue by aragilar** [pykoala/koala#7]
While we moved some code out of `__init__.py`, the file is still quite unwieldy. The next steps would be:
- [ ] Move out the remainder of the plotting code to utils (and modernise it as per #35).
- [ ] Move some of the other utility functions (e.g. the Gaussian functions) to a separate module (and look at replacing them with standard numpy/scipy functions).
- [ ] Split out the reduction class into its own module, and refactor as needed.
- [ ] Split out the other classes into their own moduels, and refactor as needed.

The ideal would be to have no code in `koala/__init__.py`, apart from a main function, which should only handle argument parsing. Everything else should be in their own modules.

**Comment by YourLocalBlake** [comment]
- [ ] Refactor classes to remove issues with relative imports

This relates to #110 and #111 where imports from koala are inside functions instead of at the top of the file.
